### ISSUE TITLE
Расскажи как пользоваться.

### ISSUE THREAD

**Issue by mrtheyann** [curly-brace/VKChecker#1]
Хотел написать тебе вк или ещё куда-нибудь, но толковых ссылок на тебя не нашёл.
Привет, можешь рассказать про то, какие зависимости тянет проект и как пользоваться.
Не умею в шарпы, но сам функционал необходим просто кровь из носу как.

Отпишись куда-нибудь, пожалуйста, буду очень признателен.
vk.com/theyann
mrtheyann@gmail.com

**Comment by curly-brace** [comment]
хай, зависимости можно посмотреть в папке packages. это либы из стандартного nuget. сам проект помоему я делал в 2012 студии. в Form1.cs надо прописать в переменныевалидный логин и пароль от вк (сам был в шоке что для доступа к сетене групп нужно иметь аккаунт в вк). и поидее должно все скомпилироваться и заработать. с другой стороны вк мог изменить свой апи за это время и часть функций может отвалиться. еще с более другой стороны обновление пакета VkNet может все починить, но может и полностью сделать код формы не работоспособным (если и там апи изменили вслед за вк). но когда я этой штукой пользовался, впринципе работало все хорошо. поддерживать я проект не хочу, так что если глюки будут таки, то сори.
